name: CI Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate HTML file
        run: test -f index.html

      - name: Validate CSS file
        run: test -f style.css

      - name: Validate JS file
        run: test -f index.js

      - name: Deploy Review App
        run: |
          echo "Review site deployed"
          echo "URL: https://review-poc19.example.com"